### ISSUE TITLE
[BUG] Doesn't wanna work on Android Chrome

### ISSUE THREAD

**Issue by Maj-ew** [bridge-core/bridge.#431]
Edit. Wait is this even GitHub for bridge v2?
I tested on 2 phones, I can't successfully 'import file' (.mcaddon / .mcpack tried .zip too; can't upload folder at all on mobile device). On PC everything works fine.
I get one of these errors every time:
1) `NotReadableError: The requested file could not be read, typically due to permission problems that have occured after a reference to file was acquired. (at window.onunhandledrejection (https://editor.bridge-core.app/assets/main.5e5952e2.js:2:694))"` so it looks like project is being created I can see all files and then it just disappears with this error.
2) `TypeError: Cannot read properties of undefined (reading 'name') (at window.onunhandlerejection (https://editor.bridge-core.app/assets/main.5e5952e2.js:2:649))`
3) `TypeError: Invalid argument expected string (at window.onunhandledrejection (https://editor.bridge-core.app/assets/main.5e5952e2.js:2:694))`
4) `Information
bridge. was unable to load data from your .mcaddon or .mcpack file because it wasn't able to find a pack manifest file inside of it.`
5) loading infinitely

These 5 errors so far on:
- OS: Android 10
- Huawei p20 pro 2018
- Chrome: 105.0.5195.136

Also tested on Huawei p20 light 2018
With a bit older Chrome and still I get same errors `and` struggle more to even make bridge. detect that I import something.

**Comment by Maj-ew** [comment]
Wrong brige version I guess?
Moved here https://github.com/bridge-core/editor/issues/625
